-- ユーザー(スキーマ)作成
-- ※ <password> は、任意のパスワードで書き換えてください。

CREATE USER ORDER_ENTRY PASSWORD <password> NO FORCE_FIRST_PASSWORD_CHANGE SET USERGROUP DEFAULT;


-- 権限設定
GRANT CATALOG READ  TO ORDER_ENTRY;
GRANT CREATE SCHEMA TO ORDER_ENTRY;
GRANT HANA_SYSRDL#CG_ADMIN_ROLE TO ORDER_ENTRY;

