-- CUSTOMERS テーブルの作成

CREATE TABLE "CUSTOMERS" (
  "CUSTOMERID" INTEGER
, "CITYID" INTEGER
, "COUNTRYID" INTEGER
, "REGIONID" INTEGER
, "CUSTOMER" NVARCHAR(50)
, "CITYNAME" NVARCHAR(50)
, "COUNTRYNAME" NVARCHAR(50)
, "REGIONNAME" NVARCHAR(50)
,  PRIMARY KEY ("CUSTOMERID")
);


-- PRODUCTS テーブルの作成

CREATE TABLE "PRODUCTS" (
  "PRODUCTID" INTEGER
, "CATEGORYID" INTEGER
, "LINEID" INTEGER 
, "PRODUCTNAME" NVARCHAR(50)
, "PRODUCTDESCRIPTION" NVARCHAR(50)
, "CATEGORYNAME" NVARCHAR(50)
, "CATEGORYDESCRIPTION" NVARCHAR(50)
, "LINENAME" NVARCHAR(50)
, "LINEDESCRIPTION" NVARCHAR(50)
, "DISCONTINUED" INTEGER 
,  PRIMARY KEY ("PRODUCTID")
);


-- ORDERS テーブル作成

CREATE TABLE "ORDERS" (
  "ORDERID" INTEGER 
, "PRODUCTID" INTEGER 
, "CUSTOMERID" INTEGER 
, "EMPLOYEEID" INTEGER 
, "ORDERPERIODID" INTEGER 
, "REQUIREDPERIODID" INTEGER 
, "SHIPPEDPERIODID" INTEGER 
, "SHIPPERID" INTEGER 
, "UNITPRICE" INTEGER 
, "QUANTITY" INTEGER 
, "DISCOUNT" INTEGER 
, "UNITSALES" BIGINT 
, "NETSALES" BIGINT 
, "UNITCOST" INTEGER 
, "COST" INTEGER
,  PRIMARY KEY ("ORDERID", "PRODUCTID")
);

